package nagariknewsDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS.
 */
public class News {

    private Long id;
    private String newsId;
    private String newsCategory;
    private String newsTitle;
    private String newsDesc;
    private String newsDate;
    private String newsImage;
    private String reportedBy;

    public News() {
    }

    public News(Long id) {
        this.id = id;
    }

    public News(Long id, String newsId, String newsCategory, String newsTitle, String newsDesc, String newsDate, String newsImage, String reportedBy) {
        this.id = id;
        this.newsId = newsId;
        this.newsCategory = newsCategory;
        this.newsTitle = newsTitle;
        this.newsDesc = newsDesc;
        this.newsDate = newsDate;
        this.newsImage = newsImage;
        this.reportedBy = reportedBy;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNewsId() {
        return newsId;
    }

    public void setNewsId(String newsId) {
        this.newsId = newsId;
    }

    public String getNewsCategory() {
        return newsCategory;
    }

    public void setNewsCategory(String newsCategory) {
        this.newsCategory = newsCategory;
    }

    public String getNewsTitle() {
        return newsTitle;
    }

    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    public String getNewsDesc() {
        return newsDesc;
    }

    public void setNewsDesc(String newsDesc) {
        this.newsDesc = newsDesc;
    }

    public String getNewsDate() {
        return newsDate;
    }

    public void setNewsDate(String newsDate) {
        this.newsDate = newsDate;
    }

    public String getNewsImage() {
        return newsImage;
    }

    public void setNewsImage(String newsImage) {
        this.newsImage = newsImage;
    }

    public String getReportedBy() {
        return reportedBy;
    }

    public void setReportedBy(String reportedBy) {
        this.reportedBy = reportedBy;
    }

}
