package nagarikschema;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nagarikschema.NewsTitle;

import nagarikschema.NewsTitleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsTitleDaoConfig;

    private final NewsTitleDao newsTitleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsTitleDaoConfig = daoConfigMap.get(NewsTitleDao.class).clone();
        newsTitleDaoConfig.initIdentityScope(type);

        newsTitleDao = new NewsTitleDao(newsTitleDaoConfig, this);

        registerDao(NewsTitle.class, newsTitleDao);
    }
    
    public void clear() {
        newsTitleDaoConfig.getIdentityScope().clear();
    }

    public NewsTitleDao getNewsTitleDao() {
        return newsTitleDao;
    }

}
