package nagarikschema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS_TITLE.
 */
public class NewsTitle {

    private Long id;
    private String title;

    public NewsTitle() {
    }

    public NewsTitle(Long id) {
        this.id = id;
    }

    public NewsTitle(Long id, String title) {
        this.id = id;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
